@startuml
'https://plantuml.com/class-diagram

class Visitor{
    + opearation1():void
    + opearation2():void
}
class ConcreteVisitor extends Visitor{
    + opearation1():void
    + opearation2():void
}
class Element{
    + accept(visitor:Visitor):void
}
class ConcreteElement extends Element{
    + accept(visitor:Visitor):void
}
Element ..> Visitor
class ObjectStructure{
    - elements:Element
}
class Client
Client ..> ObjectStructure
Client ..> Visitor
Element --o ObjectStructure
@enduml