@startuml
'https://plantuml.com/class-diagram

abstract class AbstractExpression{
    interpret():void
}
class TerminalExpression extends AbstractExpression{

}
class NonTerminalExpression extends AbstractExpression{

}
AbstractExpression --o NonTerminalExpression
class Context
class Client
Client ..> Context
Client ..> AbstractExpression
@enduml