@startuml
'https://plantuml.com/class-diagram

interface  State {
   + deduceMoney():void;
   + raffle():void;
   + dispensePrize():void;
}
class NoRaffleState implements State {

}
class CanRaffleState implements State {

}
class DispenseState implements State {

}
class DispenseOutState implements State {

}
class Active{
}
Active -- NoRaffleState
Active -- CanRaffleState
Active -- DispenseState
Active -- DispenseOutState
State --o Context
class Client
Client ..>Active
Client ..>State
@enduml