@startuml
'https://plantuml.com/class-diagram

class Handler {
    - successor: Handler
    + processRequest():void
}
class ConcreteHandlerA extends Handler {
    + processRequest():void
}
class ConcreteHandlerB extends Handler {
    + processRequest():void
}
class Request
class Client {
}
Handler --o Handler
Handler ..> Request
Client ..> Request
Client ..> Handler
@enduml