@startuml
'https://plantuml.com/class-diagram

class pizza {
+prepare():void
+bake():void
+cut():void
+box():void
}
class BJCheesePizza extends pizza {
}
class BJpepperoniPizza extends pizza {
}
class LDCheesePizza extends pizza {
}
class LDpepperoniPizza extends pizza {
}
class BJOrderPizza extends OrderPizza {
}
class LDOrderPizza extends OrderPizza{
}
LDCheesePizza <.. LDOrderPizza :依赖
LDpepperoniPizza <.. LDOrderPizza :依赖
BJCheesePizza <.. BJOrderPizza :依赖
BJpepperoniPizza <.. BJOrderPizza :依赖
@enduml